package com.aboutyou.cloud.adminapi.model;

import java.util.List;
import java.util.Map;

import com.google.gson.annotations.SerializedName;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Campaign implements ApiObjectInterface {
    /**
    * The ID of the campaign created by Backbone Core.
    */
    @SerializedName("id")
    Integer id;

    /**
    * Name of the campaign.
    */
    @SerializedName("name")
    String name;

    /**
    * Optional description of the campaign.
    */
    @SerializedName("description")
    String description;

    /**
    * List of country codes the campaign is valid for.
    */
    @SerializedName("countryCodes")
    List<String> countryCodes;

    /**
    * The reduction percentage applied to all variants, which do not have a specific reduction set.
    */
    @SerializedName("reduction")
    Double reduction;

    /**
    * Start time of campaign in Iso8601 format.
    */
    @SerializedName("startAt")
    String startAt;

    /**
    * End time of campaign in Iso8601 format.
    */
    @SerializedName("endAt")
    String endAt;

    /**
    * A specific key to identify the campaign. If not provided, it will be generated by Backbone Core.
    */
    @SerializedName("campaignKey")
    String campaignKey;

}