package com.aboutyou.cloud.adminapi.model;

import java.util.List;
import java.util.Map;

import com.google.gson.annotations.SerializedName;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ProductImage implements ApiObjectInterface {
    /**
    * Id assigned by BACKBONE Core.
    */
    @SerializedName("id")
    Integer id;

    /**
    * A key that uniquely identifies the asset within the tenant's ecosystem.
    */
    @SerializedName("referenceKey")
    String referenceKey;

    /**
    * User defined name of the image.
    */
    @SerializedName("name")
    String name;

    /**
    * MIME Type identified by BACKBONE Core.
    */
    @SerializedName("mimeType")
    String mimeType;

    /**
    * Specifies the position of the image.
    */
    @SerializedName("position")
    Integer position;

    /**
    * A source from where to upload an image.
    */
    @SerializedName("source")
    ProductImageSource source;

    /**
    * Url of the image, either manually specified or generated by BACKBONE Core, if the AY Cloud CDN is used.
    */
    @SerializedName("assetUrl")
    String assetUrl;

    /**
    * A list of attributes attached to the image.
    */
    @SerializedName("attributes")
    List<AttributeInterface> attributes;

}