package com.scayle.adminapi.model;

import java.util.List;
import java.util.Map;

import com.google.gson.annotations.SerializedName;

import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
public class Campaign extends AbstractModel  {
    /**
    * The ID of the campaign created by SCAYLE.
    */
    @SerializedName("id")
    Integer id;

    /**
    * Name of the campaign.
    */
    @SerializedName("name")
    String name;

    /**
    * Optional description of the campaign.
    */
    @SerializedName("description")
    String description;

    /**
    * List of country codes the campaign is valid for.
    */
    @SerializedName("countryCodes")
    List<String> countryCodes;

    /**
    * The reduction percentage applied to all variants, which do not have a specific reduction set.
    */
    @SerializedName("reduction")
    Double reduction;

    /**
    * Start time of campaign in Iso8601 format.
    */
    @SerializedName("startAt")
    java.time.Instant startAt;

    /**
    * End time of campaign in Iso8601 format.
    */
    @SerializedName("endAt")
    java.time.Instant endAt;

    /**
    * A specific key to identify the campaign. If not provided, it will be generated by SCAYLE.
    */
    @SerializedName("campaignKey")
    String campaignKey;

    /**
    * 
    */
    @SerializedName("customData")
    Object customData;

}