package com.scayle.adminapi.model;

import java.util.List;
import java.util.Map;

import com.google.gson.annotations.SerializedName;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PromotionTier extends AbstractModel  {
    /**
    * Autogenerated tier id
    */
    @SerializedName("id")
    Integer id;

    /**
    * 
    */
    @SerializedName("name")
    String name;

    /**
    * 
    */
    @SerializedName("effect")
    Object effect;

    /**
    * Minimal order value requirement for a tier. Value should be in a fractional currency (e.g. cents), if a currency has fractions
    */
    @SerializedName("mov")
    Integer mov;

}